[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/tv"
  to = "/public/tv.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/public/admin.html"
  status = 200
